### ISSUE TITLE
Nginx Ingress para Kubernetes

### ISSUE THREAD

**Issue by alexsandro-xpt** [aspnet/AspNetCore.Docs.pt-br#111]
Seria muito válido enfatizar neste documento se sim ou não se o Nginx Ingress do Kubernentes envia por padrão os cabelhaços X-Forwarded-For,  X-Forwarded-Proto e X-Forwarded-Host mesmo dizendo acima que: Por convenção, os proxies encaminham informações em cabeçalhos HTTP.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure o ASP.NET Core para trabalhar com servidores proxy e balanceadores de carga](https://docs.microsoft.com/pt-br/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @alexsandro-xpt ... Mudei isso para o nosso repositório. https://github.com/aspnet/AspNetCore.Docs/issues/12349

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #12356](https://github.com/aspnet/AspNetCore.Docs/issues/12356) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Olá, @alexsandro-xpt 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/aspnet/AspNetCore.Docs/issues/12356 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by alexsandro-xpt** [comment]
Bacana @CeciAc, eu tive muita duvida sobre esta questão mesmo pois estou usando o AKS com ingress NGIXN e estou com dificuldade de recuperar o IP Remoto do client, andei lendo https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers alterei o ingress, passei a ler o Header HTTP `X-Forwarded-For` e nada de conseguir o IP do conexão HTTP do client, sempre no maximo consigo o IP do LoadBalancer que no caso é o Ingress NGINX.

Ai então lendo a documentação senti falta disto na documentação pra entender melhor a situação.

**Comment by guardrex** [comment]
@alexsandro-xpt :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/12349#issuecomment-491441194
