### ISSUE TITLE
AspNetCore.App now has to be referenced in .csproj of dependent projects

### ISSUE THREAD

**Issue by lccarvalho** [aspnet/AspNetCore.Docs.pt-br#112]
I have a solution previously converted to aspnetcore 2.1 in which some projects depend on others. In this configuration I did not have to reference Microsoft.AspNetCore.App on dependent projects, only in the referenced one. Migrating to 2.2 I had to reference the metapackage in all projects. Noting that in docs could save people some time and trouble.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: cabe9331-b438-fabe-18ca-15f752ec6778
* Version Independent ID: 3294609f-b881-1fec-de04-2021b48de489
* Content: [Metapacote Microsoft.AspNetCore.App para ASP.NET Core 2.1 ou posterior](https://docs.microsoft.com/pt-br/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/metapackage-app.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/fundamentals/metapackage-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Using `Microsoft.AspNetCore.App` - AKA M.A.A in 2.1 or later is strongly recommended but not required. You never need to reference M.A.A, it's just recommended.

Recommend you closes this issue.

**Comment by lccarvalho** [comment]
Thank you Rick, but I'm not certain I understood your point. In my case, as I said, dependent projects showed no errors without the direct reference to M.A.A when using 2.1 sdk, and were plenty of them when using 2.2. The problem was solved when I put the M.A.A. (no version) reference in each project; I was just pointing you guys this phenomenon. I'll follow your recommendation and closes this issue.

**Comment by Rick-Anderson** [comment]
@lccarvalho thanks for the info. I'm not sure how we'd write that up. Generally it's best to update dependent project to M.A.A. You could open this issue from the feedback button on the [english version](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.2) that gets much higher traffic. We could see if other folks hit the problem.
