### ISSUE TITLE
Erro ao Chamar API com o JQuery

### ISSUE THREAD

**Issue by JeanFelipePereira** [aspnet/AspNetCore.Docs.pt-br#114]
Estou tendo esse erro:
Access to XMLHttpRequest at 'file:///C:/Users/user/Documents/Cursos%20Dev/Rsantos/TodoApi/wwwroot/api/todo?_=1564340880798' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Criar uma API Web com o ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @JeanFelipePereira
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Essa é uma boa mensagem de erro. Você deveria estar usando https. Onde você está recebendo esse erro? Qual versão do .NET Core você está usando?

Eu posso dizer que o código funciona.

**Comment by JeanFelipePereira** [comment]
Bom dia!
O Erro foi meu.
Não abri o index.html pela rota, abri pela pasta (direto pelo arquivo):
file:///C:/Users/user/Documents/Cursos%20Dev/Rsantos/TodoApi/wwwroot/index.html

Quando abri pela rota:
https://localhost:5001/

Funcionou!
Obrigado pela ajuda, resolvido!

**Comment by Rick-Anderson** [comment]
>Good Morning!
The mistake was mine.
I didn't open index.html by route, I opened by folder (straight from file):
file: /// C: /Users/user/Documents/Courses%20Dev/Rsantos/TodoApi/wwwroot/index.html

When I opened the route:
https: // localhost: 5001 /

It worked!
Thanks for the help, solved!
