### ISSUE TITLE
Missing information about dependency

### ISSUE THREAD

**Issue by patrickhacens** [aspnet/AspNetCore.Docs.pt-br#119]
There have been a bit of changes on blazor client-side apis and as of 3.0 it seems to be required to include `Microsoft.Aspnetcore.Components.Authorization` package as a dependency through nuget but it is not clearly defined on this page

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [Autorização e autenticação no Blazor em ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio-code#authentication)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@patrickhacens Would you mind closing this issue and re-opening it using the feedback form at the bottom of the English topic? We work these from the English repo ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/#authentication

**Comment by patrickhacens** [comment]
Ops, sorry I didn't see this was on the portuguese docs as I always use the do not translate options
will do
