### ISSUE TITLE
<MovieContext> error

### ISSUE THREAD

**Issue by henriquebg88** [aspnet/AspNetCore.Docs.pt-br#127]
For those having trouble with : 

> The type or namespace name 'MovieContext' could not be found

Instead of : 
```
    public void ConfigureServices(IServiceCollection services)
    {
        if (Environment.IsDevelopment())
        {
            services.AddDbContext<MovieContext>(options =>
            options.UseSqlite(
                Configuration.GetConnectionString("MovieContext")));
        }
        else
        {
            services.AddDbContext<MovieContext>(options =>
            options.UseSqlServer(
                Configuration.GetConnectionString("MovieContext")));
        }

        services.AddRazorPages();
    }
```

The code must be : 
```
    public void ConfigureServices(IServiceCollection services)
    {
        if (Environment.IsDevelopment())
        {
            services.AddDbContext<RazorPagesMovieContext>(options =>
            options.UseSqlite(
                Configuration.GetConnectionString("MovieContext")));
        }
        else
        {
            services.AddDbContext<RazorPagesMovieContext>(options =>
            options.UseSqlServer(
                Configuration.GetConnectionString("MovieContext")));
        }

        services.AddRazorPages();
    }
```
Just change **MovieContext** for **RazorPagesMovieContext**
:1st_place_medal: 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Adicionar um modelo a um aplicativo Páginas Razor no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @henriquebg88
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Thanks, this is being tracked in https://github.com/aspnet/AspNetCore.Docs/issues/15729

**Comment by ticianaciminari** [comment]
Hello, @henriquebg88,

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/15729. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
